apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "airflow.name" . }}
    helm.sh/chart: {{ include "airflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: scheduler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "airflow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: scheduler
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "airflow.name" . }}
        helm.sh/chart: {{ include "airflow.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: scheduler
    {{- if .Values.podAnnotations }}
      annotations:
      {{ toYaml .Values.podAnnotations | nindent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end -}}
    {{- with .Values.affinity }}
      affinity:
      {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
      {{ toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- include "airflow.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- if and .Values.airflow.cloneDagFilesFromGit.enabled (not .Values.airflow.dagsConfigMap) }}
      initContainers:
      - name: git-clone-repository
        image: "{{ template "git.image" . }}"
        imagePullPolicy: {{ .Values.git.pullPolicy | quote }}
        command: [ '/bin/sh', '-c' , 'git clone {{ .Values.airflow.cloneDagFilesFromGit.repository }} /dags && cd /dags && git checkout {{ .Values.airflow.cloneDagFilesFromGit.revision }}']
        volumeMounts:
        - name: custom-dag-files
          mountPath: /dags
      {{- end }}
      containers:
      - name: airflow-scheduler
        image: {{ template "airflow.schedulerImage" . }}
        imagePullPolicy: {{ .Values.schedulerImage.pullPolicy | quote }}
        env:
        {{- if .Values.schedulerImage.debug }}
        - name: BASH_DEBUG
          value: "1"
        - name: NAMI_DEBUG
          value: "1"
        - name: NAMI_LOG_LEVEL
          value: "trace8"
        {{- end }}
        - name: AIRFLOW_DATABASE_NAME
          {{- if .Values.postgresql.enabled }}
          value: {{ .Values.postgresql.postgresqlDatabase }}
          {{- else }}
          value: {{ .Values.externalDatabase.database | quote }}
          {{- end }}
        - name: AIRFLOW_DATABASE_USERNAME
          {{- if .Values.postgresql.enabled }}
          value: {{ .Values.postgresql.postgresqlUsername }}
          {{- else }}
          value: {{ .Values.externalDatabase.user | quote }}
          {{- end }}
        - name: AIRFLOW_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.postgresql.enabled }}
              name: {{ template "airflow.postgresql.fullname" . }}
              key: postgresql-password
            {{- else }}
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
            {{- end }}
        - name: AIRFLOW_DATABASE_HOST
          {{- if .Values.postgresql.enabled }}
          value: {{ template "airflow.postgresql.fullname" . }}
          {{- else }}
          value: {{ .Values.externalDatabase.host | quote }}
          {{- end }}
        - name: AIRFLOW_DATABASE_PORT_NUMBER
          {{- if .Values.postgresql.enabled }}
          value: "5432"
          {{- else }}
          value: {{ .Values.externalDatabase.port | quote }}
          {{- end }}
        - name: REDIS_HOST
          {{- if .Values.redis.enabled }}
          value: {{ template "airflow.redis.fullname" . }}
          {{- else }}
          value: {{ .Values.externalRedis.host | quote }}
          {{- end }}
        - name: REDIS_PORT_NUMBER
          {{- if .Values.redis.enabled }}
          value: "6379"
          {{- else }}
          value: {{ .Values.externalRedis.port | quote }}
          {{- end }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.redis.enabled }}
              name: {{ template "airflow.redis.secretName" . }}
              key: redis-password
            {{- else }}
              name: {{ printf "%s-%s" .Release.Name "externalredis" }}
              key: redis-password
            {{- end }}
        - name: AIRFLOW_EXECUTOR
          value: "CeleryExecutor"
        - name: AIRFLOW_FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.airflow.auth.existingSecret }}{{ .Values.airflow.auth.existingSecret }}{{ else }}{{ template "airflow.fullname" . }}{{ end }}
              key: airflow-fernetKey
        - name: AIRFLOW_WEBSERVER_HOST
          value: {{ template "airflow.fullname" . }}
        - name: AIRFLOW_LOAD_EXAMPLES
          {{- if .Values.airflow.loadExamples }}
          value: "yes"
          {{- else }}
          value: "no"
          {{- end }}
        {{- if .Values.airflow.extraEnvVars }}
          {{ toYaml .Values.airflow.extraEnvVars | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
        {{- end }}
        volumeMounts:
        {{- if or (.Files.Glob "files/dags/*.py") .Values.airflow.dagsConfigMap .Values.airflow.cloneDagFilesFromGit.enabled }}
        - name: custom-dag-files
          mountPath: /opt/bitnami/airflow/dags
        {{- end }}
        {{- if .Values.airflow.airflowConfigurationConfigMap }}
        - name: custom-configuration-file
          mountPath: /opt/bitnami/airflow/airflow.cfg
          subPath: airflow.cfg
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      {{- if or (.Files.Glob "files/dags/*.py") .Values.airflow.dagsConfigMap .Values.airflow.cloneDagFilesFromGit.enabled }}
      - name: custom-dag-files
        {{- if or (.Files.Glob "files/dags/*.py") .Values.airflow.dagsConfigMap }}
        configMap:
          name: {{ template "airflow.dagFilesConfigMap" . }}
        {{- else if .Values.airflow.cloneDagFilesFromGit.enabled }}
        emptyDir: {}
        {{- end }}
      {{- end }}
      {{- if .Values.airflow.airflowConfigurationConfigMap }}
      - name: custom-configuration-file
        configMap:
          name: {{ .Values.airflow.airflowConfigurationConfigMap }}
      {{- end }}