dependencies:
- name: postgresql
  version: 5.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 8.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
